#!/usr/bin/ruby
require 'syslog'
require 'yaml'
require 'rexml/document'

=begin

== NAME

libvirt-manager

== DESCRIPTION

Wrapper to allow management of single VMs via ssh

== USAGE

  ssh -4t user@host help|start|shutdown|destroy|status|vnc

== INSTALL

1. create an account, add several ssh keys, adding the vm name to the command=

  adduser user

1b. restrict logins to rbash

  chsh user /bin/rbash

2. put user into group vmowner

  adduser user vmowner

3. visudo (clear env?)

  Cmnd_Alias VMMAN = /usr/local/sbin/libvirt-manager
  Defaults:%vmowner !env_reset
  %vmowner ALL=NOPASSWD: VMMAN

4. limit ssh key and enforce this wrapper skript, includes users vm name

  command="sudo /usr/local/sbin/libvirt-manager vmname",permitopen="127.0.0.1:5901",no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa

5. dynamic vnc port for every user in libvirt vm config

  <graphics type='vnc' port='-1' autoport='no' keymap='en-us'/>

6. create host config (/etc/libvirt/user_vm.yaml)

  ---
  vnc_host: 127.0.0.1
  server_name: libvirt.example.com
  auth_file: /home/vm/.ssh/authorized_keys


=end

VIR_CMD = '/usr/bin/virsh'
VIR_URI = 'qemu:///system'
CONFIG_FILE = '/etc/libvirt/user_vm.yaml'
NIL_PORT=5920
VERBOSE = 1

def exit_error(msg)
  Syslog.open($0, Syslog::LOG_PID | Syslog::LOG_CONS) { |s| s.warning msg }
  STDERR.puts(msg) if VERBOSE
  exit 1
end

def get_vnc_port(vm)
  # what vnc port for this vm?
  domain = `virsh dumpxml #{vm}`
  doc = REXML::Document.new(domain).root
  port = ''
  doc.elements.each('/domain/devices/graphics') { |vnc| port = vnc.attributes['port'] }
  exit_error('no vnc port') unless (port and port.match(/^59\d\d$/))
  return port
end

def update_authorized_keys(vm, port)
  has_port=%r{command="sudo /usr/local/sbin/libvirt-manager (.+)",permitopen="#{@config['vnc_host']}:#{port}"}
  has_vm=%r{command="sudo /usr/local/sbin/libvirt-manager #{vm}",permitopen="#{@config['vnc_host']}:(\d+)"}
  result = []
  File.open(@config['auth_file']) { |file|
    file.each { |line|
      if (line =~ has_vm)
        result << <<-__END__
command="sudo /usr/local/sbin/libvirt-manager #{vm}",permitopen="#{@config['vnc_host']}:#{port}"#{$'}
        __END__
      elsif (line =~ has_port)
        result << <<-__END__
command="sudo /usr/local/sbin/libvirt-manager #{$1}",permitopen="#{@config['vnc_host']}:#{NIL_PORT}"#{$'}
        __END__
      else
        result << line
      end
    }
  }
  File.open(@config['auth_file'], 'w') { |file|
    result.each { |line|
      file.puts(line.chomp)
    }
  }
end

# we are running with uid 0
@config = File.open(CONFIG_FILE) { |yf| YAML::load(yf) }

# which user connected?
@user = ENV['SUDO_USER'] || exit_error('invalid caller')
@user.gsub(/[^a-z]/,'')
@vm = ARGV[0] || exit_error('no vm')

usage_help = proc {
  puts "usage:"
  puts "  ssh #{@user}@#{@config['server_name']} start|shutdown|destroy|status"
  puts "  ssh -4t -L5900:#{@config['vnc_host']}:#{@vnc_port} #{@user}@#{@config['server_name']} vnc"
  puts
  STDOUT.flush
}

case ENV['SSH_ORIGINAL_COMMAND']
  when /^start$/
    system(VIR_CMD, '-c', VIR_URI, 'start', @vm)
  when /^shutdown$/
    system(VIR_CMD, '-c', VIR_URI, 'shutdown', @vm)
  when /^destroy$/
    system(VIR_CMD, '-c', VIR_URI, 'destroy', @vm)
  when /^status$/
    system(VIR_CMD, '-c', VIR_URI, 'dominfo', @vm)
  when /^vnc$/
    ENV['SSH_TTY'] || exit_error('no tty. use ssh -t')
    @vnc_port = get_vnc_port(@vm)
    update_authorized_keys(@vm, @vnc_port)
    puts "usage:"
    puts "  ssh -4t -L5900:#{@config['vnc_host']}:#{@vnc_port} #{@user}@#{@config['server_name']} vnc"
    puts "  vinagre :0"
    puts
    puts "<ctrl-c> to abort tunnel"
    STDOUT.flush
    sleep
  else
    @vnc_port = get_vnc_port(@vm)
    update_authorized_keys(@vm, @vnc_port)
    usage_help.call if VERBOSE
end

exit 0
